language: php

php:
  - 5.3
  - 5.4
  - 5.5

addons:
  sauce_connect: true

env:
  global:
    # sauce_labs credentials
    - secure: "Hld917J5CADMf7ox/Q3k4TdVjfBbYGyXaswfFDRyWoR5GfS1wpBDEcB+XMCEJ8Y8g94LBb7JJLD6XrUTgPJEZTolLivMSeDfcIqITHOa4N3tJgArhY6ISB94wuckl54c2wtEucrmJJo/k3clgtP34iS86RgptRWwdXTN09C5H8Q="
    - secure: "E1f7LdsnccUnfDuwE3STdzuKl9TknI5bQFUdhUUCM4F1C8qToneRegUW/dctkNf00Wa2U/SRT55CdYbf8Xh4JFl/CPRxdBb+0MVD9GGHSetuWaB5qmOwgLVfboE7F8mGFfgJKEiUkXeHj9c6StUuvKNRz732p1AAcSpypLnH5p0="
  matrix:
    - WP_VERSION=latest
    - WP_VERSION=3.9.1  WP_MULTISITE=0
    - WP_VERSION=3.8.1  WP_MULTISITE=0

#before_install:
#  - sudo apt-get -y -qq update
#  - sudo apt-get -y -qq install curl libcurl3-gnutls libgnutls26

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit

notifications:
  slack: insideout10:NcslbQWVmD4YPInDq8TpBIno#helixware